language: node_js
node_js:
  - "11"
before_install:
  - mv .env.dist .env
  - npm install
  - npm run server &
script:
  - npm run build
  - npm run lint
  - npm run test
  - npm run doc
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
