language: node_js
services:
  - mongodb
node_js:
  - "11"
before_install:
  - mv .env.dist .env
  - npm install
script:
  - npm run server &
  - npm run build
  - npm run lint
  - npm run test
  - npm run doc
before_script:
  - sleep 15
  - mongorestore docs/scaffolding/test-data/
deploy:
  local-dir: docs/frontend
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
