language: node_js
services:
  - mongodb
env:
  - MONGO_DB=mongodb://travis:test@127.0.0.1:27017/dsa
node_js:
  - "11"
before_install:
  - mv .env.dist .env
  - npm install
script:
  - npm run server &
  - npm run build
  - npm run lint
  - npm run test
  - npm run doc
before_script:
  - sleep 15
  - mongo dsa --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
  - mongorestore docs/scaffolding/mongo-database/
deploy:
  local-dir: docs/frontend
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
